name: CustomRegex
version: 1.1.3
description: Use regular expressions for chat manipulation.
author: "0-o#9646"
main: ml.customregex.Main

commands:
    customregex:
        description: Commands for Custom Regex Plugin
        aliases: [cr, cregex, customr, regex]
        permission: zerodasho.customregex.generic
permissions:
    zerodasho.customregex.generic:
        default: true
    zerodasho.customregex.generic.reload:
        default: op
